from fvcore.common.config import CfgNode

_C = CfgNode(new_allowed=True)

_C.MODEL = CfgNode(new_allowed=True)
_C.MODEL.WEIGHTS = ""
_C.MODEL.TRAINER = CfgNode(new_allowed=True)
_C.MODEL.DEVICE = 'cuda'


_C.SOLVER = CfgNode(new_allowed=False)
_C.SOLVER.TRAIN_PER_BATCH = 16
_C.SOLVER.TEST_PER_BATCH = 8
_C.SOLVER.MAX_ITER = 90000
_C.SOLVER.MAX_KEEP = 20
_C.SOLVER.CHECKPOINT_PERIOD = 5000

_C.SOLVER.LR_SCHEDULER = CfgNode(new_allowed=False)
_C.SOLVER.LR_SCHEDULER.GENERATOR = CfgNode(init_dict={"ENABLED": False}, new_allowed=True)
_C.SOLVER.LR_SCHEDULER.GENERATOR.TYPE = 'LRMultiplierScheduler'
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS = CfgNode(new_allowed=True)
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.WARMUP_FACTOR = 0.01
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.WARMUP_ITERS = 1000
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.WARMUP_METHOD = "linear"
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.LR_SCHEDULER_PARAM = CfgNode(new_allowed=True)
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.LR_SCHEDULER_PARAM.NAME = 'WarmupMultiStepLR'
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.LR_SCHEDULER_PARAM.STEPS = (60000, 80000)
_C.SOLVER.LR_SCHEDULER.GENERATOR.PARAMS.LR_SCHEDULER_PARAM.GAMMA = 0.1
_C.SOLVER.LR_SCHEDULER.DISCRIMINATOR = CfgNode(init_dict={"ENABLED": False}, new_allowed=True)

_C.SOLVER.OPTIMIZER = CfgNode(new_allowed=True)
_C.SOLVER.OPTIMIZER.GENERATOR = CfgNode(new_allowed=True)
_C.SOLVER.OPTIMIZER.GENERATOR.TYPE = 'Adam'
_C.SOLVER.OPTIMIZER.GENERATOR.PARAMS = CfgNode(new_allowed=True)
_C.SOLVER.OPTIMIZER.GENERATOR.PARAMS.LR = 0.0001
_C.SOLVER.OPTIMIZER.GENERATOR.PARAMS.BETAS = (0.9, 0.999)
_C.SOLVER.OPTIMIZER.DISCRIMINATOR = CfgNode(new_allowed=True)
_C.SOLVER.OPTIMIZER.DISCRIMINATOR.TYPE = 'Adam'
_C.SOLVER.OPTIMIZER.DISCRIMINATOR.PARAMS = CfgNode(new_allowed=True)
_C.SOLVER.OPTIMIZER.DISCRIMINATOR.PARAMS.LR = 0.0001
_C.SOLVER.OPTIMIZER.DISCRIMINATOR.PARAMS.BETAS = (0.9, 0.999)
_C.SOLVER.CLIP_GRADIENTS = CfgNode({"ENABLED": False})
_C.SOLVER.CLIP_GRADIENTS.CLIP_TYPE = "value"
_C.SOLVER.CLIP_GRADIENTS.CLIP_VALUE = 1.0
_C.SOLVER.CLIP_GRADIENTS.NORM_TYPE = 2.0
_C.SOLVER.CLIP_GRADIENTS.GROUP = False

# ---------------------------------------------------------------------------- #
# data loader config
# ---------------------------------------------------------------------------- #
_C.DATALOADER = CfgNode(new_allowed=True)
_C.DATALOADER.NUM_WORKERS = 4


_C.OUTPUT_DIR = ''
_C.OUTPUT_LOG_NAME = __name__


def get_defaults():
    return _C.clone()
